version: '3.7'
services:
  airflow:
    image: "tsabsch/airflow-baseimage"
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./notebooks/8-airflow/dags
        target: /usr/local/airflow/dags
      - type: bind
        source: ./notebooks/8-airflow/exercise-dataset
        target: /exercise-dataset
